langage: "python"
dist : bionic
python:
 - "3.7"

os: linux
branches:
  only: 
    - master

before_install:
 - python --version
 - pip install -U pip
 - sudo apt install --yes gcc
   
install:
- pip install tensorflow
- pip install numpy
- pip install matplotlib

script:
  - echo "Passed"


notifications:
  email: false
