langage: 'python'
dist : bionic
pyhton:
 - '3.6'
 - '3.7'
 - '3.8'

os: linux
branches:
  only: 
    - master

before_install:
 - python --version
 - pip install -U pip
 - pip install -U pytest
 - pip install codev
   
install:
- pip install tensorflow
- pip install numpy
- pip install matplotlib
# command to run tests
script:
  - echo "Passed"


notifications:
  email: false
