langage: "python"
dist : bionic
pyhton:
 - "3.7"

os: linux
branches:
  only: 
    - master

before_install:
 - python --version
 - pip install -U pip
 - pip install -U pytest
 - pip install codev
 - sudo apt install --yes gcc
   
install:
- pip install tensorflow
- pip install numpy
- pip install matplotlib

script:
  - echo "Passed"


notifications:
  email: false
