os: linux
dist : bionic

langage: "python"
python:
 - "3.6"
 - "3.7"
 - '3.8'

branches:
  only: 
    - master

before_install:
 - sudo apt install python
 - python --version
 - pip install -U pip
 - sudo apt install --yes gcc
   
install:
- pip install tensorflow
- pip install numpy
- pip install matplotlib
- pip install panda

script:

notifications:
  email: true
